config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "robots#new"

  resources :robots, only: [:new, :create]
end

app/models/robot.rb
class Robot
  def initialize(params)
    @setup = params
    @position_x = params[:start_x].to_i
    @position_y = params[:start_y].to_i 
  end

  def move
    return "configuração inválida" unless validate_location

    x = @position_x
    y = @position_y

    moves = @setup[:moves].split(" ")
    moves.each do |move|
      steps = move[0, move.size-1].to_i
      direction = move[move.size-1, move.size]

      y = @position_y + steps if direction == "N"
      y = @position_y - steps if direction == "S"
      x = @position_x + steps if direction == "L"
      x = @position_x - steps if direction == "O"

      break unless validate_position(x, y)
        
      @position_x = x
      @position_y = y
    end

    "Inicio (#{@setup[:start_x]}, #{@setup[:start_y]}) / Movimento [#{@setup[:moves]}] / Posição Final: (#{@position_x},#{@position_y})"
  end

  def validate_position(x, y)
    valid = x <= @setup[:size_x].to_i && x >= 0
    valid &= y <= @setup[:size_y].to_i && y >= 0
  end

  def validate_location
    valid = @setup[:size_x].to_i > 0 && @setup[:size_x].to_i < 1_000_000_000
    valid &= @setup[:size_y].to_i > 0 && @setup[:size_y].to_i < 1_000_000_000
    valid &= validate_position(@setup[:start_x].to_i, @setup[:start_y].to_i)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  def show
  end

  def new
    @message = params[:message] if params[:message]
    @robot = nil
  end

  def create
    @robot = Robot.new(params)

    redirect_to new_robot_path(message: "#{@robot.move}")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/robots_helper.rb
module RobotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Robotmars</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/robots/new.html.erb
<h1>Controle Remoto do Robo de Marte</h1>

<p>Insira os parâmetros de configuração do terreno e do movimento a ser enviado para Marte!</p>

<%= form_with model: @robot, url: robots_path do |form| %>
  <p>
    <%= form.label :size_x %><br>
    <%= form.text_field :size_x %>
  </p>

  <p>
    <%= form.label :size_y %><br>
    <%= form.text_field :size_y %>
  </p>
 
  <p>
    <%= form.label :start_x %><br>
    <%= form.text_field :start_x %>
  </p>

  <p>
    <%= form.label :start_y %><br>
    <%= form.text_field :start_y %>
  </p>

  <p>
    <%= form.label :moves %><br>
    <%= form.text_area :moves %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

<h1>RESULTADO</h1>
<% if @message %> 
  <h3 class="mensagem"><%= @message %></h3>
<% end %>